site_name: "Pocket Docs"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.full_width   # Enable full-width content area
  palette:
    scheme: light
  font:
    text: "Helvetica Neue, Helvetica, Arial, sans-serif"
    code: "Menlo, Monaco, Courier New, monospace"

docs_dir: docs

nav:
  - Home: index.md

  - Getting Started:
      - Quick Start: guide.md
      - Setup Steps: preparation.md
      - Key Abstractions: core_abstraction.md

  - Core Concepts:
      - Agent Basics: agent.md
      - Node Fundamentals: node.md
      - Understanding Flows: flow.md
      - Data Structures: structure.md

  - Features & Extensions:
      - Async Processing: async.md
      - Batch Operations: batch.md
      - Communication Patterns: communication.md
      - Task Decomposition: decomp.md
      - Large Language Models: llm.md
      - MapReduce Workflows: mapreduce.md
      - Memory & Caching: memory.md
      - Multi-Agent Systems: multi_agent.md
      - Parallel Execution: parallel.md
      - Retrieval Augmented Generation: rag.md
      - Tool Integrations: tool.md

  - Additional Resources:
      - Sample Applications: apps.md
      - Conceptual Paradigms: paradigm.md
      - Visualizations: viz.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - codehilite
