site_name: Pocket Flow Framework
theme:
  name: terminal

nav:
  - Home: index.md
  - Guide: guide.md
  - Core Concepts:
    - Core Abstraction: core_abstraction.md
    - Understanding Flows: flow.md
    - Task Decomposition: decomp.md
  - Implementation:
    - Setup: preparation.md
  - Applications: apps.md

plugins:
  - search